# ---------------------------------------------------------------------------------------------------------------------
# Discord –∫–æ–Ω—Ñ–∏–≥—É—Ä–∞—Ü–∏—è
# –¢–æ–∫–µ–Ω –±–æ—Ç–∞
Bot_Token: NzE4Mzk0MTE4NDEzMjIxODg4.XtoOqA.DAOu0uJ4Q31XsWLLIWZaTLrYiZ0

# –ü—Ä–µ—Ñ–∏–∫—Å –±–æ—Ç–∞
Prefix: ","

# –ß–∞—Ç –¥–ª—è –∫–æ–º–∞–Ω–¥—ã –±–æ—Ç–∞
bot_channel: [817912568789073920, 781617697930084372]

# –ß–∞—Ç—ã –≥–¥–µ –±—É–¥–µ—Ç –∏–¥—Ç–∏ XP
talk_channels: [817699782893633646, 817702727622197308, 827300322169847828]

# –ß–∞—Ç –∫—É–¥–∞ –±—É–¥—É—Ç –ø—Ä–∏—Ö–æ–¥–∏—Ç—å —Å–æ–æ–±—â–µ–Ω–∏—è join leave
join_leave_message: False

# ID –∫–∞–Ω–∞–ª–∞, –≥–¥–µ –±—É–¥–µ—Ç join leave
join_leave_channel: 

# –†–æ–ª—å –∫–æ—Ç–æ—Ä–∞—è –±—É–¥–µ—Ç –≤—ã–¥–æ–≤–∞—Ç—å—Å—è –ø—Ä–∏ –∑–∞—Ö–æ–¥–µ –Ω–∞ —Å–µ—Ä–≤–µ—Ä
on_join_role: 'üëç| Member'
add_role: False

# –í–∫–ª—é—á–∏—Ç—å –ª–æ–≥–∏
enable_log: True

# –ê–Ω—Ç–∏—Å–ø–∞–º —Å–∏—Å—Ç–µ–º–∞
antispam_system: False
# ---------------------------------------------------------------------------------------------------------------------
# –ù–∞—Å—Ç—Ä–æ–π–∫–∞ —É—Ä–æ–≤–Ω—è
# –û–ø—ã—Ç –∑–∞ –æ–¥–Ω–æ —Å–æ–æ–±—â–µ–≥–∏–µ
xp_per_message: 5

# –°–∫–æ–ª—å–∫–æ –æ–ø—ã—Ç–∞ –Ω—É–∂–Ω–æ –¥–æ –ø–æ–≤—ã—à–µ–Ω–∏—è —É—Ä–æ–≤–Ω—è. 
xp_per_level: 100

# –£–¥–≤–æ–∏—Ç–µ–ª—å XP —Ä–æ–ª—å:
double_xp: ""

# Customise the Progress Bar emojis on the Stats Menu (Text will work too, if you want that?)
completed_bar: ":white_large_square:"
uncompleted_bar: ":black_large_square:"

# –£—Ä–æ–≤–Ω–∏ –∑–∞ —Ä–æ–ª–∏
level_roles: ["1 —É—Ä–æ–≤–µ–Ω—å —Ä–æ–ª—å", "2 —É—Ä–æ–≤–µ–Ω—å —Ä–æ–ª—å", "3 —É—Ä–æ–≤–µ–Ω—å —Ä–æ–ª—å"]
level_roles_num: [1, 2, 3]

# –°—Ç–∞—Ç—É—Å –±–æ—Ç–∞
bot_status_text: "–Æ–∫–∏–æ"

# –ê–∫—Ç–∏–≤–Ω–æ—Å—Ç—å –±–æ—Ç–∞: IDLE, DND, ONLINE, OFFLINE
bot_activity: online

# –ê–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ç–∏–≤–Ω—ã–µ —Ä–æ–ª–∏
admin_role: "‚Ä¢ Íí∞ üêß–ê–¥–º–∏–Ω–∏—Å—Ç—Ä–∞—Ü–∏—è Íí± ÀéÀäÀó ‚Ä¢" 

# –ü–æ–∫–∞–∑—ã–≤–∞—Ç—å —Å–æ–æ–±—â–µ–Ω–∏–µ –æ –ø–æ–≤—ã—à–µ–Ω–∏–∏ —É—Ä–æ–≤–Ω—è
show_levelup_message: False

# –ü–æ–∫–∞–∑—ã–≤–∞—Ç—å —Å–æ–æ–±—â–µ–Ω–∏–µ –æ –≤—ã–¥–∞—á–∏ –Ω–æ–≤–æ–π —Ä–æ–ª–∏
show_newrole_message: False

# alias –¥–ª—è rank
rank_alias: ['r', 'level', 'l', 'stats', 'xp', 'progress']
# ---------------------------------------------------------------------------------------------------------------------
# –ù–∞—Å—Ç—Ä–æ–π–∫–∞ —Ä–µ–π—Ç–∏–Ω–≥–∞ —É—á–∞—Å—Ç–Ω–∏–∫–æ–≤
# –ö–æ–ª-–≤–æ —É—á–∞—Å—Ç–Ω–∏–∫–æ–≤ –≤ —Ç–æ–ø–µ —Ä–µ–π—Ç–∏–Ω–≥–∞
leaderboard_amount: 10

# –ò–∑–æ–æ–±—Ä–∞–∂–µ–Ω–∏–µ 
leaderboard_image: "https://cdn.discordapp.com/attachments/809363224663031829/809734218103259146/leaderboards.png"

# aliases –¥–ª—è leaderboard
leaderboard_alias: ['lb', 'leader', 'rankings']

# –ë—É–¥–µ—Ç –æ—Ç–ø—Ä–∞–≤–ª—è—Ç—å –∏–∑–æ–±—Ä–∞–∂–µ–Ω–∏–µ, –∞ –Ω–µ –≤—Å—Ç—Ä–∞–∏–≤–∞–Ω–∏–µ - –ª—É—á—à–µ –¥–ª—è –º–æ–±–∏–ª—å–Ω—ã—Ö –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ–π –∏ –ø—Ä–æ—â–µ –¥–ª—è —á—Ç–µ–Ω–∏—è. –ü–†–ò–ú–ï–ß–ê–ù–ò–ï. –ò–Ω–æ–≥–¥–∞ –æ—Ç–ø—Ä–∞–≤–∫–∞ –∏–∑–æ–±—Ä–∞–∂–µ–Ω–∏—è –º–æ–∂–µ—Ç –∑–∞–Ω—è—Ç—å –Ω–µ—Å–∫–æ–ª—å–∫–æ —Å–µ–∫—É–Ω–¥, –Ω–æ –æ–Ω–æ –Ω–µ –¥–æ–ª–∂–Ω–æ –±—ã—Ç—å –∑–∞–º–µ—Ç–Ω—ã–º.
image_mode: True
# ---------------------------------------------------------------------------------------------------------------------
# Embed –Ω–∞—Å—Ç—Ä–æ–π–∫–∞
# Rank Embed –¶–≤–µ—Ç | --------------------------------
rank_embed_colour: 0x2F3136

# Leaderboard Embed –¶–≤–µ—Ç | --------------------------------
leaderboard_embed_colour: 0x2F3136

# Embed –¶–≤–µ—Ç | --------------------------------
embed_colour: 0x2F3136

# –û—à–∏–±–∫–∞ Embed –¶–≤–Ω—Ç | --------------------------------
error_embed_colour: 0xFF0000

# –£—Å–ø–µ—Ö Embed –¶–≤–µ—Ç | --------------------------------
success_embed_colour: 0x00FF00
# ---------------------------------------------------------------------------------------------------------------------
# Help Config
# True/False - <prefix>help command
help_command: True
# ---------------------------------------------------------------------------------------------------------------------





